<a href="https://colab.research.google.com/github/fereshtehdehkhoda/Example-48-SVC/blob/main/S16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv("hw16_train.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  99 non-null     float64
 1   sepal_width   99 non-null     float64
 2   petal_length  99 non-null     float64
 3   petal_width   99 non-null     float64
 4   class         99 non-null     object 
dtypes: float64(4), object(1)
memory usage: 4.0+ KB


In [ ]:
features=['sepal_length','sepal_width','petal_length','petal_width']
X_train=data[features]

y_train=data['class']

In [ ]:
y_train.value_counts(normalize=True)

class
Iris-versicolor    0.353535
Iris-virginica     0.333333
Iris-setosa        0.313131
Name: proportion, dtype: float64

In [ ]:
round(data['petal_length'].corr(data['petal_width'],method='pearson'),2)*100

96.0

In [ ]:
#soale 2

In [ ]:
data.shape

(99, 5)

In [ ]:
from sklearn.linear_model import LogisticRegression
model_1=LogisticRegression(penalty=None,
                          multi_class='multinomial',
                          max_iter=100,
                          solver='lbfgs')

model_1.fit(X_train,y_train)
print(model_1.coef_)
print(model_1.intercept_)

[[  3.76972083  12.57041855 -20.64419778  -9.56460636]
 [ -1.29524822  -4.30190842   5.88672301  -2.90153595]
 [ -2.47447261  -8.26851013  14.75747477  12.46614231]]
[  2.42267148  24.23436885 -26.65704033]


In [ ]:
y_train_prob_1=model_1.predict_proba(X_train)
y_train_prob_1

array([[1.00000000e+00, 2.65391546e-11, 4.60101416e-35],
       [9.99999959e-01, 4.12876080e-08, 2.36565692e-31],
       [1.00000000e+00, 6.38147535e-12, 4.66800792e-36],
       [1.00000000e+00, 5.78355664e-11, 2.48499998e-33],
       [9.99999997e-01, 2.64640339e-09, 1.03908969e-32],
       [9.99982052e-01, 1.79480437e-05, 4.27934455e-28],
       [9.99999307e-01, 6.93253556e-07, 1.00670941e-29],
       [1.00000000e+00, 2.21061571e-12, 1.64761605e-36],
       [9.99999897e-01, 1.03470577e-07, 1.24879699e-30],
       [9.99999775e-01, 2.24915947e-07, 4.84006306e-31],
       [9.99999999e-01, 9.88996268e-10, 2.68123687e-34],
       [1.00000000e+00, 6.45209436e-19, 6.37725351e-45],
       [1.00000000e+00, 1.36164160e-17, 9.58770560e-42],
       [1.00000000e+00, 1.42331818e-15, 1.75964871e-39],
       [1.00000000e+00, 4.04651921e-11, 1.81867937e-34],
       [1.00000000e+00, 3.51294168e-11, 3.38860291e-34],
       [1.00000000e+00, 1.19097691e-15, 4.01752577e-41],
       [9.99987177e-01, 1.28234

In [ ]:
#soale 3

In [ ]:
data_test=pd.read_csv("hw16_test.csv")

In [ ]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   class         50 non-null     object 
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [ ]:
features_test=['sepal_length','sepal_width','petal_length','petal_width']
X_test=data_test[features_test]

y_test=data_test['class']

In [ ]:
y_pred=model_1.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print("accuracy :",round(accuracy_score(y_test,y_pred),3)*100)

accuracy : 98.0


In [ ]:
#soale 4

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_2=KNeighborsClassifier(n_neighbors=20,
                            weights='uniform',
                            algorithm='auto',
                            metric='minkowski')
model_2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [ ]:
y_test_pred_2=model_2.predict(X_test)
y_test_pred_2

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [ ]:
print("accuracy: ",round(accuracy_score(y_test,y_test_pred_2),2)*100)

accuracy:  92.0


In [ ]:
#soale 5

In [ ]:
from sklearn.model_selection import cross_val_score
params_grid=[1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
cv_scores=np.zeros(shape=len(params_grid))
for i in range(len(params_grid)):
    knn=KNeighborsClassifier(n_neighbors = params_grid[i],
                               weights = 'uniform',
                               algorithm = 'auto',
                               metric = 'minkowski')
    scores=cross_val_score(estimator=knn,
                          X=X_train,
                          y=y_train,
                          scoring='accuracy',
                          cv=5,n_jobs=-1)
    cv_scores[i]=scores.mean()


In [ ]:
params_grid[np.argmax(cv_scores)]

10

In [ ]:
#soale 6

In [ ]:
model_3=KNeighborsClassifier(n_neighbors = 10,
                               weights = 'uniform',
                               algorithm = 'auto',
                               metric = 'minkowski')

model_3.fit(X_train,y_train)


KNeighborsClassifier(n_neighbors=10)

In [ ]:
y_test_pred_3=model_3.predict(X_test)
print("accuracy: ", round(accuracy_score(y_test,y_test_pred_3),2)*100)

accuracy:  98.0


In [ ]:
#soale 7

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_4=RandomForestClassifier(n_estimators=100,
                              max_depth=5,
                              max_features=2,
                              min_samples_leaf=5,
                              ccp_alpha=0)

model_4.fit(X_train,y_train)

RandomForestClassifier(ccp_alpha=0, max_depth=5, max_features=2,
                       min_samples_leaf=5)

In [ ]:
y_test_pred_4=model_4.predict(X_test)
print("Accuracy: ",round(accuracy_score(y_test,y_test_pred_4),2)*100)

Accuracy:  96.0


In [ ]:
#soale 8

In [ ]:
import itertools
n_estimator=[50,100,200]
max_features=['sqrt', 'log2', None]
max_depth=[1,3,5]
min_samples_leaf=[5,10,15]
param_grid=list(itertools.product(n_estimator,max_features,max_depth,min_samples_leaf))

param_grid=pd.DataFrame(data=param_grid,
                       index=range(1,82),columns=['n_estimator','max_features','max_depth','min_samples_leaf'])

param_grid

,n_estimator,max_features,max_depth,min_samples_leaf
1,50,sqrt,1,5
2,50,sqrt,1,10
3,50,sqrt,1,15
4,50,sqrt,3,5
5,50,sqrt,3,10
...,...,...,...,...
77,200,None,3,10
78,200,None,3,15
79,200,None,5,5
80,200,None,5,10


In [ ]:
from sklearn.model_selection import cross_val_score
cv_scores=np.zeros(shape=len(param_grid))

for i in range(len(param_grid)):
    rf_c=RandomForestClassifier(n_estimators=param_grid.iloc[i,0],
                               max_features=param_grid.iloc[i,1],
                               max_depth=param_grid.iloc[i,2],
                               min_samples_leaf=param_grid.iloc[i,3],
                               ccp_alpha=0,

                               )
    scores=cross_val_score(estimator=rf_c,
                          X=X_train,
                          y=y_train,
                          scoring='accuracy',
                          cv=5,n_jobs=-1)
    cv_scores[i]=scores.mean()

In [ ]:
param_grid.iloc[np.argmax(cv_scores)]

n_estimator           50
max_features        log2
max_depth              3
min_samples_leaf      15
Name: 15, dtype: object

In [ ]:
model_5=RandomForestClassifier(n_estimators=param_grid.iloc[np.argmax(cv_scores),0],
                               max_features=param_grid.iloc[np.argmax(cv_scores),1],
                               max_depth=param_grid.iloc[np.argmax(cv_scores),2],
                               min_samples_leaf=param_grid.iloc[np.argmax(cv_scores),3],
                               ccp_alpha=0)

model_5.fit(X_train,y_train)

RandomForestClassifier(ccp_alpha=0, max_depth=3, max_features='log2',
                       min_samples_leaf=15, n_estimators=50)

In [ ]:
y_test_pred_5=model_5.predict(X_test)
print("Accuracy: ",round(accuracy_score(y_test,y_test_pred_5),2)*100)

Accuracy:  96.0


In [ ]:
#soale 9

In [ ]:
degree_grid=[2,3,4]
c_reg= 10 ** np.linspace(-3, 3, 7)
params_grid=list(itertools.product(degree_grid,c_reg))
params_grid=pd.DataFrame(data=params_grid,index=range(1,22),columns=['degree_grid','c_reg'])
params_grid

,degree_grid,c_reg
1,2,0.001
2,2,0.010
3,2,0.100
4,2,1.000
5,2,10.000
6,2,100.000
7,2,1000.000
8,3,0.001
9,3,0.010
10,3,0.100


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
from sklearn.svm import SVC
cv_scores=np.zeros(shape=len(params_grid))

for i in range(len(params_grid)):
    svc=SVC(kernel='poly',
           degree=params_grid.iloc[i,0],
           C=params_grid.iloc[i,1])
    scores=cross_val_score(estimator=svc,
                          X=X_train_scaled,
                          y=y_train,
                          cv=5,scoring='accuracy')
    cv_scores[i]=scores.mean()


In [ ]:
params_grid.iloc[np.argmax(cv_scores)]

degree_grid      3.0
c_reg          100.0
Name: 13, dtype: float64

In [ ]:
svc=SVC(kernel='poly',
           degree=params_grid.iloc[np.argmax(cv_scores),0],
           C=params_grid.iloc[np.argmax(cv_scores),1])

model_6=svc.fit(X_train_scaled,y_train)

In [ ]:
y_test_pred_6=model_6.predict(X_test_scaled)
print("Accuracy: ", round(accuracy_score(y_test,y_test_pred_6),2)*100)

Accuracy:  96.0


In [ ]:
#soale 10

In [ ]:
sample=pd.read_csv("sample.csv")

In [ ]:
X_=['sepal_length','sepal_width','petal_length','petal_width']
X_sample=sample[X_]

In [ ]:
sample.head()

,sepal_length,sepal_width,petal_length,petal_width,class
0,6,3,4.5,1.2,NaN


In [ ]:
y_logreg=model_1.predict(X_sample)
y_logreg

array(['Iris-versicolor'], dtype=object)

In [ ]:
y_knn=model_3.predict(X_sample)
y_knn

array(['Iris-versicolor'], dtype=object)

In [ ]:
y_randomforest=model_5.predict(X_sample)
y_randomforest

array(['Iris-versicolor'], dtype=object)

In [ ]:
X_sample_scaled=scaler.fit_transform(X_sample)

In [ ]:
y_SVC=model_6.predict(X_sample_scaled)
y_SVC

array(['Iris-versicolor'], dtype=object)